apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: my-deployment
spec:
  containers:
  - name: my-ubuntu
    image: rvenkat1220/my-ubuntu:BUILD_NUMBER
    tty: true
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 256Mi
  - name: my-archlinux
    image: rvenkat1220/my-archlinux:BUILD_NUMBER
    tty: true
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 256Mi
  nodeSelector:
    kubernetes.io/os: linux
  dnsConfig:
    options:
      - name: ndots
        value: "2"
